/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameScene from "./scripts/GameScene"
import GameController from "./scripts/GameController"
import LevelScene from "./scripts/LevelScene"
import PauseDialog from "./scripts/PauseDialog"
import StartScene from "./scripts/StartScene"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="exactfit";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="scenes/StartScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("scripts/GameScene.ts",GameScene);
        reg("scripts/GameController.ts",GameController);
        reg("scripts/LevelScene.ts",LevelScene);
        reg("scripts/PauseDialog.ts",PauseDialog);
        reg("scripts/StartScene.ts",StartScene);
    }
}
GameConfig.init();